# Site settings
title:       Asper.me
email:       mutahhir.ali@gmail.com
author:      Mutahhir Ali Hayat
description: "Writings about my learning"
baseurl:     "asper.me"
url:         "http://asper.me"

# Google analytics
google_analytics: UA-55273957-1

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username: mutahhir
stackoverflow_id: mutahhir
twitter_username: mutahhir
google_plus_id: mutahhir
linkedin_username: mutahhir
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: true

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
